services:
  palforge:
    build: .
    container_name: palforge
    ports:
      - "8080:8080"
      - "8211-8220:8211-8220/udp"
    volumes:
      - ./servers:/app/servers
      - ./steamcmd:/app/steamcmd
      - ./data:/app/data
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - SERVER_DATA_DIR=/app/servers
      - STEAMCMD_DIR=/app/steamcmd
      - DATA_DIR=/app/data
    restart: unless-stopped
